# Generated by Django 3.2.5 on 2021-07-10 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kakei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.PositiveSmallIntegerField(verbose_name='支出項目')),
                ('cost_year', models.PositiveSmallIntegerField(choices=[(2020, '2020年'), (2021, '2021年'), (2022, '2022年'), (2023, '2023年'), (2024, '2024年'), (2025, '2025年')], verbose_name='年')),
                ('cost_month', models.PositiveSmallIntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], verbose_name='月')),
                ('cost_value', models.IntegerField(help_text='円\u3000※半角入力', verbose_name='金額')),
                ('memo', models.TextField(blank=True, max_length=50, null=True, verbose_name='メモ')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('entry_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '家計簿',
                'verbose_name_plural': '家計簿',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=15, verbose_name='支出項目')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
