# Generated by Django 3.2.5 on 2021-07-10 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakeibo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kakei',
            new_name='Kakeibo',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '支出項目', 'verbose_name_plural': '支出項目'},
        ),
    ]
