# Generated by Django 3.2.5 on 2021-07-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo_app', '0002_auto_20210710_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='cost_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakeibo_app.item', verbose_name='支出項目'),
        ),
    ]
