# Generated by Django 3.2.5 on 2021-07-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo_app', '0003_alter_kakeibo_cost_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cost_name',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='kakeibo',
            old_name='entry_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='kakeibo',
            old_name='cost_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='kakeibo',
            old_name='cost_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='kakeibo',
            name='cost_name',
        ),
        migrations.RemoveField(
            model_name='kakeibo',
            name='cost_value',
        ),
        migrations.AddField(
            model_name='kakeibo',
            name='cost',
            field=models.CharField(default=1, max_length=15, verbose_name='支出項目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kakeibo',
            name='value',
            field=models.IntegerField(default=1, verbose_name='金額'),
            preserve_default=False,
        ),
    ]
